import { normalizeLanguageCode } from "@/i18n/languages";

export interface CountryInfo {
  code: string;
  timezone: string;
}

export const COUNTRIES: CountryInfo[] = [
  { code: "AD", timezone: "Europe/Andorra" },
  { code: "AE", timezone: "Asia/Dubai" },
  { code: "AF", timezone: "Asia/Kabul" },
  { code: "AG", timezone: "America/Antigua" },
  { code: "AI", timezone: "America/Anguilla" },
  { code: "AL", timezone: "Europe/Tirane" },
  { code: "AM", timezone: "Asia/Yerevan" },
  { code: "AO", timezone: "Africa/Luanda" },
  { code: "AQ", timezone: "Antarctica/McMurdo" },
  { code: "AR", timezone: "America/Argentina/Buenos_Aires" },
  { code: "AS", timezone: "Pacific/Pago_Pago" },
  { code: "AT", timezone: "Europe/Vienna" },
  { code: "AU", timezone: "Australia/Lord_Howe" },
  { code: "AW", timezone: "America/Aruba" },
  { code: "AX", timezone: "Europe/Mariehamn" },
  { code: "AZ", timezone: "Asia/Baku" },
  { code: "BA", timezone: "Europe/Sarajevo" },
  { code: "BB", timezone: "America/Barbados" },
  { code: "BD", timezone: "Asia/Dhaka" },
  { code: "BE", timezone: "Europe/Brussels" },
  { code: "BF", timezone: "Africa/Ouagadougou" },
  { code: "BG", timezone: "Europe/Sofia" },
  { code: "BH", timezone: "Asia/Bahrain" },
  { code: "BI", timezone: "Africa/Bujumbura" },
  { code: "BJ", timezone: "Africa/Porto-Novo" },
  { code: "BL", timezone: "America/St_Barthelemy" },
  { code: "BM", timezone: "Atlantic/Bermuda" },
  { code: "BN", timezone: "Asia/Brunei" },
  { code: "BO", timezone: "America/La_Paz" },
  { code: "BQ", timezone: "America/Kralendijk" },
  { code: "BR", timezone: "America/Noronha" },
  { code: "BS", timezone: "America/Nassau" },
  { code: "BT", timezone: "Asia/Thimphu" },
  { code: "BW", timezone: "Africa/Gaborone" },
  { code: "BY", timezone: "Europe/Minsk" },
  { code: "BZ", timezone: "America/Belize" },
  { code: "CA", timezone: "America/St_Johns" },
  { code: "CC", timezone: "Indian/Cocos" },
  { code: "CD", timezone: "Africa/Kinshasa" },
  { code: "CF", timezone: "Africa/Bangui" },
  { code: "CG", timezone: "Africa/Brazzaville" },
  { code: "CH", timezone: "Europe/Zurich" },
  { code: "CI", timezone: "Africa/Abidjan" },
  { code: "CK", timezone: "Pacific/Rarotonga" },
  { code: "CL", timezone: "America/Santiago" },
  { code: "CM", timezone: "Africa/Douala" },
  { code: "CN", timezone: "Asia/Shanghai" },
  { code: "CO", timezone: "America/Bogota" },
  { code: "CR", timezone: "America/Costa_Rica" },
  { code: "CU", timezone: "America/Havana" },
  { code: "CV", timezone: "Atlantic/Cape_Verde" },
  { code: "CW", timezone: "America/Curacao" },
  { code: "CX", timezone: "Indian/Christmas" },
  { code: "CY", timezone: "Asia/Nicosia" },
  { code: "CZ", timezone: "Europe/Prague" },
  { code: "DE", timezone: "Europe/Berlin" },
  { code: "DJ", timezone: "Africa/Djibouti" },
  { code: "DK", timezone: "Europe/Copenhagen" },
  { code: "DM", timezone: "America/Dominica" },
  { code: "DO", timezone: "America/Santo_Domingo" },
  { code: "DZ", timezone: "Africa/Algiers" },
  { code: "EC", timezone: "America/Guayaquil" },
  { code: "EE", timezone: "Europe/Tallinn" },
  { code: "EG", timezone: "Africa/Cairo" },
  { code: "EH", timezone: "Africa/El_Aaiun" },
  { code: "ER", timezone: "Africa/Asmara" },
  { code: "ES", timezone: "Europe/Madrid" },
  { code: "ET", timezone: "Africa/Addis_Ababa" },
  { code: "FI", timezone: "Europe/Helsinki" },
  { code: "FJ", timezone: "Pacific/Fiji" },
  { code: "FK", timezone: "Atlantic/Stanley" },
  { code: "FM", timezone: "Pacific/Chuuk" },
  { code: "FO", timezone: "Atlantic/Faroe" },
  { code: "FR", timezone: "Europe/Paris" },
  { code: "GA", timezone: "Africa/Libreville" },
  { code: "GB", timezone: "Europe/London" },
  { code: "GD", timezone: "America/Grenada" },
  { code: "GE", timezone: "Asia/Tbilisi" },
  { code: "GF", timezone: "America/Cayenne" },
  { code: "GG", timezone: "Europe/Guernsey" },
  { code: "GH", timezone: "Africa/Accra" },
  { code: "GI", timezone: "Europe/Gibraltar" },
  { code: "GL", timezone: "America/Nuuk" },
  { code: "GM", timezone: "Africa/Banjul" },
  { code: "GN", timezone: "Africa/Conakry" },
  { code: "GP", timezone: "America/Guadeloupe" },
  { code: "GQ", timezone: "Africa/Malabo" },
  { code: "GR", timezone: "Europe/Athens" },
  { code: "GS", timezone: "Atlantic/South_Georgia" },
  { code: "GT", timezone: "America/Guatemala" },
  { code: "GU", timezone: "Pacific/Guam" },
  { code: "GW", timezone: "Africa/Bissau" },
  { code: "GY", timezone: "America/Guyana" },
  { code: "HK", timezone: "Asia/Hong_Kong" },
  { code: "HN", timezone: "America/Tegucigalpa" },
  { code: "HR", timezone: "Europe/Zagreb" },
  { code: "HT", timezone: "America/Port-au-Prince" },
  { code: "HU", timezone: "Europe/Budapest" },
  { code: "ID", timezone: "Asia/Jakarta" },
  { code: "IE", timezone: "Europe/Dublin" },
  { code: "IL", timezone: "Asia/Jerusalem" },
  { code: "IM", timezone: "Europe/Isle_of_Man" },
  { code: "IN", timezone: "Asia/Kolkata" },
  { code: "IO", timezone: "Indian/Chagos" },
  { code: "IQ", timezone: "Asia/Baghdad" },
  { code: "IR", timezone: "Asia/Tehran" },
  { code: "IS", timezone: "Atlantic/Reykjavik" },
  { code: "IT", timezone: "Europe/Rome" },
  { code: "JE", timezone: "Europe/Jersey" },
  { code: "JM", timezone: "America/Jamaica" },
  { code: "JO", timezone: "Asia/Amman" },
  { code: "JP", timezone: "Asia/Tokyo" },
  { code: "KE", timezone: "Africa/Nairobi" },
  { code: "KG", timezone: "Asia/Bishkek" },
  { code: "KH", timezone: "Asia/Phnom_Penh" },
  { code: "KI", timezone: "Pacific/Tarawa" },
  { code: "KM", timezone: "Indian/Comoro" },
  { code: "KN", timezone: "America/St_Kitts" },
  { code: "KP", timezone: "Asia/Pyongyang" },
  { code: "KR", timezone: "Asia/Seoul" },
  { code: "KW", timezone: "Asia/Kuwait" },
  { code: "KY", timezone: "America/Cayman" },
  { code: "KZ", timezone: "Asia/Almaty" },
  { code: "LA", timezone: "Asia/Vientiane" },
  { code: "LB", timezone: "Asia/Beirut" },
  { code: "LC", timezone: "America/St_Lucia" },
  { code: "LI", timezone: "Europe/Vaduz" },
  { code: "LK", timezone: "Asia/Colombo" },
  { code: "LR", timezone: "Africa/Monrovia" },
  { code: "LS", timezone: "Africa/Maseru" },
  { code: "LT", timezone: "Europe/Vilnius" },
  { code: "LU", timezone: "Europe/Luxembourg" },
  { code: "LV", timezone: "Europe/Riga" },
  { code: "LY", timezone: "Africa/Tripoli" },
  { code: "MA", timezone: "Africa/Casablanca" },
  { code: "MC", timezone: "Europe/Monaco" },
  { code: "MD", timezone: "Europe/Chisinau" },
  { code: "ME", timezone: "Europe/Podgorica" },
  { code: "MF", timezone: "America/Marigot" },
  { code: "MG", timezone: "Indian/Antananarivo" },
  { code: "MH", timezone: "Pacific/Majuro" },
  { code: "MK", timezone: "Europe/Skopje" },
  { code: "ML", timezone: "Africa/Bamako" },
  { code: "MM", timezone: "Asia/Yangon" },
  { code: "MN", timezone: "Asia/Ulaanbaatar" },
  { code: "MO", timezone: "Asia/Macau" },
  { code: "MP", timezone: "Pacific/Saipan" },
  { code: "MQ", timezone: "America/Martinique" },
  { code: "MR", timezone: "Africa/Nouakchott" },
  { code: "MS", timezone: "America/Montserrat" },
  { code: "MT", timezone: "Europe/Malta" },
  { code: "MU", timezone: "Indian/Mauritius" },
  { code: "MV", timezone: "Indian/Maldives" },
  { code: "MW", timezone: "Africa/Blantyre" },
  { code: "MX", timezone: "America/Mexico_City" },
  { code: "MY", timezone: "Asia/Kuala_Lumpur" },
  { code: "MZ", timezone: "Africa/Maputo" },
  { code: "NA", timezone: "Africa/Windhoek" },
  { code: "NC", timezone: "Pacific/Noumea" },
  { code: "NE", timezone: "Africa/Niamey" },
  { code: "NF", timezone: "Pacific/Norfolk" },
  { code: "NG", timezone: "Africa/Lagos" },
  { code: "NI", timezone: "America/Managua" },
  { code: "NL", timezone: "Europe/Amsterdam" },
  { code: "NO", timezone: "Europe/Oslo" },
  { code: "NP", timezone: "Asia/Kathmandu" },
  { code: "NR", timezone: "Pacific/Nauru" },
  { code: "NU", timezone: "Pacific/Niue" },
  { code: "NZ", timezone: "Pacific/Auckland" },
  { code: "OM", timezone: "Asia/Muscat" },
  { code: "PA", timezone: "America/Panama" },
  { code: "PE", timezone: "America/Lima" },
  { code: "PF", timezone: "Pacific/Tahiti" },
  { code: "PG", timezone: "Pacific/Port_Moresby" },
  { code: "PH", timezone: "Asia/Manila" },
  { code: "PK", timezone: "Asia/Karachi" },
  { code: "PL", timezone: "Europe/Warsaw" },
  { code: "PM", timezone: "America/Miquelon" },
  { code: "PN", timezone: "Pacific/Pitcairn" },
  { code: "PR", timezone: "America/Puerto_Rico" },
  { code: "PS", timezone: "Asia/Gaza" },
  { code: "PT", timezone: "Europe/Lisbon" },
  { code: "PW", timezone: "Pacific/Palau" },
  { code: "PY", timezone: "America/Asuncion" },
  { code: "QA", timezone: "Asia/Qatar" },
  { code: "RE", timezone: "Indian/Reunion" },
  { code: "RO", timezone: "Europe/Bucharest" },
  { code: "RS", timezone: "Europe/Belgrade" },
  { code: "RU", timezone: "Europe/Kaliningrad" },
  { code: "RW", timezone: "Africa/Kigali" },
  { code: "SA", timezone: "Asia/Riyadh" },
  { code: "SB", timezone: "Pacific/Guadalcanal" },
  { code: "SC", timezone: "Indian/Mahe" },
  { code: "SD", timezone: "Africa/Khartoum" },
  { code: "SE", timezone: "Europe/Stockholm" },
  { code: "SG", timezone: "Asia/Singapore" },
  { code: "SH", timezone: "Atlantic/St_Helena" },
  { code: "SI", timezone: "Europe/Ljubljana" },
  { code: "SJ", timezone: "Arctic/Longyearbyen" },
  { code: "SK", timezone: "Europe/Bratislava" },
  { code: "SL", timezone: "Africa/Freetown" },
  { code: "SM", timezone: "Europe/San_Marino" },
  { code: "SN", timezone: "Africa/Dakar" },
  { code: "SO", timezone: "Africa/Mogadishu" },
  { code: "SR", timezone: "America/Paramaribo" },
  { code: "SS", timezone: "Africa/Juba" },
  { code: "ST", timezone: "Africa/Sao_Tome" },
  { code: "SV", timezone: "America/El_Salvador" },
  { code: "SX", timezone: "America/Lower_Princes" },
  { code: "SY", timezone: "Asia/Damascus" },
  { code: "SZ", timezone: "Africa/Mbabane" },
  { code: "TC", timezone: "America/Grand_Turk" },
  { code: "TD", timezone: "Africa/Ndjamena" },
  { code: "TF", timezone: "Indian/Kerguelen" },
  { code: "TG", timezone: "Africa/Lome" },
  { code: "TH", timezone: "Asia/Bangkok" },
  { code: "TJ", timezone: "Asia/Dushanbe" },
  { code: "TK", timezone: "Pacific/Fakaofo" },
  { code: "TL", timezone: "Asia/Dili" },
  { code: "TM", timezone: "Asia/Ashgabat" },
  { code: "TN", timezone: "Africa/Tunis" },
  { code: "TO", timezone: "Pacific/Tongatapu" },
  { code: "TR", timezone: "Europe/Istanbul" },
  { code: "TT", timezone: "America/Port_of_Spain" },
  { code: "TV", timezone: "Pacific/Funafuti" },
  { code: "TW", timezone: "Asia/Taipei" },
  { code: "TZ", timezone: "Africa/Dar_es_Salaam" },
  { code: "UA", timezone: "Europe/Simferopol" },
  { code: "UG", timezone: "Africa/Kampala" },
  { code: "UM", timezone: "Pacific/Midway" },
  { code: "US", timezone: "America/New_York" },
  { code: "UY", timezone: "America/Montevideo" },
  { code: "UZ", timezone: "Asia/Samarkand" },
  { code: "VA", timezone: "Europe/Vatican" },
  { code: "VC", timezone: "America/St_Vincent" },
  { code: "VE", timezone: "America/Caracas" },
  { code: "VG", timezone: "America/Tortola" },
  { code: "VI", timezone: "America/St_Thomas" },
  { code: "VN", timezone: "Asia/Ho_Chi_Minh" },
  { code: "VU", timezone: "Pacific/Efate" },
  { code: "WF", timezone: "Pacific/Wallis" },
  { code: "WS", timezone: "Pacific/Apia" },
  { code: "XK", timezone: "Europe/Belgrade" },
  { code: "YE", timezone: "Asia/Aden" },
  { code: "YT", timezone: "Indian/Mayotte" },
  { code: "ZA", timezone: "Africa/Johannesburg" },
  { code: "ZM", timezone: "Africa/Lusaka" },
  { code: "ZW", timezone: "Africa/Harare" },
];

const countryDisplayNamesCache = new Map<string, Intl.DisplayNames>();

const getCountryDisplayNames = (language: string): Intl.DisplayNames => {
  const normalizedLanguage = normalizeLanguageCode(language);
  const cached = countryDisplayNamesCache.get(normalizedLanguage);
  if (cached) return cached;

  const displayNames = new Intl.DisplayNames([normalizedLanguage], { type: "region" });
  countryDisplayNamesCache.set(normalizedLanguage, displayNames);
  return displayNames;
};

export const getCountryTimezone = (countryCode: string): string => {
  const code = countryCode.toUpperCase();
  const country = COUNTRIES.find((item) => item.code === code);
  return country?.timezone ?? "UTC";
};

export const getCountryName = (countryCode: string, language: string): string => {
  const code = countryCode.toUpperCase();
  return getCountryDisplayNames(language).of(code) ?? code;
};

export const getCountryOptions = (language: string): Array<{ code: string; label: string; timezone: string }> => {
  return COUNTRIES
    .map((country) => ({
      code: country.code,
      label: getCountryName(country.code, language),
      timezone: country.timezone,
    }))
    .sort((a, b) => a.label.localeCompare(b.label));
};
